bookshelf.CustomUser
DEBUG", "SECURE_BROWSER_XSS_FILTER", "X_FRAME_OPTIONS", "SECURE_CONTENT_TYPE_NOSNIFF", "CSRF_COOKIE_SECURE", "SESSION_COOKIE_SECURE
SECURE_SSL_REDIRECT
SECURE_HSTS_SECONDS", "31536000
SECURE_HSTS_INCLUDE_SUBDOMAINS
SECURE_PROXY_SSL_HEADER", "HTTP_X_FORWARDED_PROTO", "https
